### ISSUE TITLE
Equalizing - little bug

### ISSUE THREAD

**Issue by Husky5383** [gagax1234/OpenFunscripter#11]
I'm not sure, but I think I found a little bug. Whenever I equalize spacing between strokes the last stroke is always offset from the rest:
![image](https://user-images.githubusercontent.com/66775885/112869754-c8fa5600-90bd-11eb-8888-913860b5ecbe.png)

And this is the lenght of the rest of equalized strokes:
![image](https://user-images.githubusercontent.com/66775885/112869765-cbf54680-90bd-11eb-925a-2ce3023057b0.png)

**Comment by gagax1234** [comment]
Where you using it on a large selection?
Because in that case I did find a way to improve the precision.

The way I did the math before meant that the remainder of the division was lost too early which would make it less precise the longer the selection. 0d24346d 

You can check if this still happens with this version.
https://ci.appveyor.com/project/gagax1234/openfunscripter/builds/38458349/artifacts

**Comment by gagax1234** [comment]
I should say that +-1 ms differences when equalizing are to be expected because in funscripts the ms are always whole numbers and can't be a fraction.

**Comment by Husky5383** [comment]
I usually used it on 30+ sec sections. The new version fixed it, now it's perfect.

+-1 ms differences are totally fine. Earlier it could move the whole section of the equalized strokes by around 1 frame and it was messing up with my OCD because the strokes seemed to not follow the beat anymore 😄 It's all good now, thank you!
