### ISSUE TITLE
Backup not working properly, maybe path length issue...

### ISSUE THREAD

**Issue by scriptingsentinel** [gagax1234/OpenFunscripter#8]
I realized that a lot of my scripting projects never got backed up during scripting sessions. This is what I see for my current project:
> ERROR: Failed to save: "C:\Users\xxxxx\AppData\Roaming\OFS\OFS_data\backup\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST_17-47-4.funscript.backup"
> Couldn't open C:\Users\xxxxx\AppData\Roaming\OFS\OFS_data\backup\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST\WankzVR-G
> 

The binary folder for OFS is:
_H:\Scripting\OFS-1.1.6\OpenFunscripter.exe_

My project folder is:
_H:\Scripting\Ongoing\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team_
Located in that folder are two files:
_WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST.mp4
WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST.funscript_

My best guess is a path length or buffer length issue. The _couldn't open_ path is 127 characters long in my log.

I also noted that the file to save contains the same folder name twice. That seems unnecessary. Can't it be shortened to:
_"C:\Users\xxxx\AppData\Roaming\OFS\OFS_data\backup\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST\WankzVR-Gina Valentina, Liza Rowe - Tailgate tag team - 2048p_FAST_17-47-4.funscript.backup"_

**Comment by gagax1234** [comment]
I thought I fixed that issue in 1.1.6 😞 
There used to be a fixed size buffer of a 1024 characters which I got rid of because I assumed it was too small and replaced it with a dynamic stringstream but the issue here seems to be different.

the error message was truncated the path was fine.
It was the windows path length limit, which is 260 by default 🤮 
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

anyway I was able to reproduce and fix it. 6b20265559434438531b3a9655a55fa51d8be08e
I also got rid of the extra directory it used to be that every loaded script got a folder but since there's only one backup per script this doesn't make sense anymore.
